<a href="https://colab.research.google.com/github/Jaswanth270602/Diabetes_Prediction/blob/main/Diabetis_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.preprocessing import StandardScaler

In [ ]:
diabetes_data = pd.read_csv('/content/diabetes.csv')

In [ ]:
diabetes_data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
diabetes_data['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [ ]:
x = diabetes_data.drop('Outcome',axis=1)

In [ ]:
y= diabetes_data['Outcome']

In [ ]:
x.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [ ]:
y.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [ ]:
scaler = StandardScaler()

In [ ]:
scaler.fit(x)

StandardScaler()

In [ ]:
std_data = scaler.transform(x)
std_data

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [ ]:
x=std_data
x


array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,stratify=y,random_state=1)
x_train

array([[-2.50952128e-01,  3.30087080e-03, -8.84314245e-01, ...,
         5.08618960e-01, -1.04156736e+00, -7.01198424e-01],
       [ 1.23388019e+00,  1.72464386e+00,  1.08020025e+00, ...,
         2.16704696e-01, -1.47270110e-02,  2.10669743e+00],
       [-8.44885053e-01, -2.78373437e-01,  5.63222752e-01, ...,
         3.56315866e-01, -7.69756680e-01, -7.86286177e-01],
       ...,
       [-5.47918591e-01,  1.12999810e+00,  2.53036252e-01, ...,
         9.40144394e-01, -1.02042653e+00, -2.75759658e-01],
       [-1.14185152e+00,  2.22380888e-01, -5.71502470e-02, ...,
        -1.89436889e-01,  2.77586265e+00, -7.01198424e-01],
       [-8.44885053e-01,  1.84983245e+00, -3.57259724e+00, ...,
         1.43512945e+00, -5.73448966e-01,  6.60205626e-01]])

In [ ]:
classifier = svm.SVC(kernel='linear')

In [ ]:
classifier.fit(x_train,y_train)

SVC(kernel='linear')

In [ ]:
y_train_pred = classifier.predict(x_train)
accuracy = accuracy_score(y_train_pred,y_train)
accuracy

0.7833876221498371

In [ ]:
y_test_pred = classifier.predict(x_test)
accuracy = accuracy_score(y_test_pred,y_test)
accuracy

0.7792207792207793

In [ ]:
pred_data = (9,156,86,28,155,34.3,1.189,42)
pred_data_np = np.asarray(pred_data)
pred_data_np_reshape = pred_data_np.reshape(1,-1)
std_pred_data = scaler.transform(pred_data_np_reshape)
result = classifier.predict(std_pred_data)
print(result)
if(result[0] == 0):
  print("Person does not have diabetes")
else:
  print("This person is suffering from diabetes")

[1]
This person is suffering from diabetes


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
